#EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 40010
  tomcat: 
    max-threads: 10 

logging: 
  config: classpath:logback.xml
  
spring: 
  thymeleaf: 
    cache: false
  profiles: 
    active: development
    
security: 
  basic: 
    enabled: true
  user: 
    name: root
    password: 123456
  ignored: /health,/refresh,/bus/refresh,/info
  



---
spring:
  profiles: development
zookeeper: 
  servers: 130.252.100.20:2181

servers: 
  - '130.252.100.20,dev'
  - '130.252.100.21,test'
  - '130.252.101.105,卢衡'
  - '127.0.0.1,本地'
  
---
spring:
  profiles: production
zookeeper: 
  servers: 172.27.232.75:2181


servers: 
  - '172.27.232.76,Nginx'
  - '172.27.232.73,Windows跳板机'
  - '127.0.0.1,本地'
  - '172.27.232.79,passport-s1'
  - '172.27.232.85,passport-s2'
     
     
---
spring:
  profiles: proth
zookeeper: 
  servers: 172.27.232.96:2181


servers: 
  - '172.27.232.98,Nginx-th'
  - '172.27.232.73,Windows跳板机'
  - '127.0.0.1,本地'
  - '172.27.232.101,web-s1-th'
  - '172.27.232.102,web-s2-th'
  - '172.27.232.103,provider-s1-th'
  - '172.27.232.105,task-s1-th'
  - '172.27.232.99,java-wallet-th'
     